language: java
# use Java 8
jdk:
- oraclejdk11

before_install:
  - cd ./CCC

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

after_success:
  - bash <(curl -s https://codecov.io/bash)
